import '../onboarding_one_screen/widgets/label_item_widget.dart';import 'models/label_item_model.dart';import 'models/onboarding_one_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:rudra_s_application2/core/app_export.dart';import 'package:rudra_s_application2/widgets/app_bar/appbar_subtitle_one.dart';import 'package:rudra_s_application2/widgets/app_bar/custom_app_bar.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'provider/onboarding_one_provider.dart';class OnboardingOneScreen extends StatefulWidget {const OnboardingOneScreen({Key? key}) : super(key: key);

@override OnboardingOneScreenState createState() =>  OnboardingOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => OnboardingOneProvider(), child: OnboardingOneScreen()); } 
 }
class OnboardingOneScreenState extends State<OnboardingOneScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgOnboardingOne), fit: BoxFit.cover)), child: Container(height: 718.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 361.v, width: 283.h, alignment: Alignment.topCenter), _buildLabel(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 49.v, actions: [AppbarSubtitleOne(text: "lbl_skip".tr, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), onTap: () {onTapMediumLabelMedium(context);})]); } 
/// Section Widget
Widget _buildLabel(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(height: 335.v, width: 327.h, margin: EdgeInsets.only(bottom: 5.v), child: Stack(alignment: Alignment.bottomCenter, children: [Consumer<OnboardingOneProvider>(builder: (context, provider, child) {return CarouselSlider.builder(options: CarouselOptions(height: 335.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {provider.sliderIndex = index;}), itemCount: provider.onboardingOneModelObj.labelItemList.length, itemBuilder: (context, index, realIndex) {LabelItemModel model = provider.onboardingOneModelObj.labelItemList[index]; return LabelItemWidget(model);});}), Align(alignment: Alignment.bottomCenter, child: Consumer<OnboardingOneProvider>(builder: (context, provider, child) {return Container(height: 10.v, margin: EdgeInsets.only(bottom: 112.v), child: AnimatedSmoothIndicator(activeIndex: provider.sliderIndex, count: provider.onboardingOneModelObj.labelItemList.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 12, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.41), dotHeight: 10.v, dotWidth: 10.h)));}))]))); } 
/// Navigates to the signUpCreateAcountScreen when the action is triggered.
onTapMediumLabelMedium(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpCreateAcountScreen, ); } 
 }
